export default {
  setRuntimeVariable: 'SET_RUNTIME_VARIABLE',
  loginUserRequest: 'LOGIN_USER_REQUEST',
  loginUserFailure: 'LOGIN_USER_FAILURE',
  loginUserSuccess: 'LOGIN_USER_SUCCESS',
  logoutUser: 'LOGOUT_USER',
  fetchProtectedDataRequest: 'FETCH_PROTECTED_DATA_REQUEST',
  receiveProtectedData: 'RECEIVE_PROTECTED_DATA',
  openDecisionSupport: 'OPEN_DECISION_SUPPORT',
  showChatBubble: 'SHOW_CHAT_BUBBLE',
  showChatError: 'SHOW_CHAT_ERROR',
  notificationsCount: 'NOTIFICATIONS_COUNT',
  openConsole: 'OPEN_CONSOLE',
  closeConsole: 'CLOSE_CONSOLE',
  addGlobalNotification: 'ADD_GLOBAL_NOTIFICATION',
  ignoreGlobalNotification: 'IGNORE_GLOBAL_NOTIFICATION',
};
