/* eslint-disable import/prefer-default-export */


export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const ACTION_TYPES = {
 LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
 LOGIN_USER_FAILURE:'LOGIN_USER_FAILURE',
 LOGIN_USER_SUCCESS:'LOGIN_USER_SUCCESS',
 LOGOUT_USER:'LOGOUT_USER',
 FETCH_PROTECTED_DATA_REQUEST:'FETCH_PROTECTED_DATA_REQUEST',
 RECEIVE_PROTECTED_DATA:'RECEIVE_PROTECTED_DATA',
};